"use client";
import { useEffect, useMemo, useState } from "react";
import dynamic from "next/dynamic";
const MapCanvas=dynamic(()=>import('../components/Globe'),{ssr:false});
const countries=['Afghanistan','Albania','Algeria','Andorra','Angola','Argentina','Armenia','Australia','Austria','Azerbaijan','Bahamas','Bahrain','Bangladesh','Belgium','Brazil','Canada','Chile','China','Colombia','Croatia','Czechia','Denmark','Egypt','Finland','France','Georgia','Germany','Ghana','Greece','Hungary','Iceland','India','Indonesia','Ireland','Israel','Italy','Japan','Jordan','Kazakhstan','Kenya','Kuwait','Malaysia','Mexico','Morocco','Nepal','Netherlands','New Zealand','Nigeria','Norway','Pakistan','Peru','Philippines','Poland','Portugal','Qatar','Romania','Russia','Saudi Arabia','Singapore','South Africa','South Korea','Spain','Sri Lanka','Sweden','Switzerland','Thailand','Turkey','Ukraine','United Arab Emirates','United Kingdom','United States','Vietnam','Zambia','Zimbabwe'];
type Lead={place_id:string;name:string;phone:string;rating:number|null;review_count:number;categories:string[];city:string;state:string;website:string;domain:string;email:string;address:string;business_status:string;claimed:boolean|null;working_hours:string[];google_maps_url:string;zip_code:string;lat:number|null;lng:number|null};
type Opportunity='all'|'noWebsite'|'highRated'|'phone'|'unclaimed';
const examples=['London','Shibuya, Tokyo','Downtown Toronto','Chennai'];
const filters:[Opportunity,string,string][]=[['all','All businesses','◎'],['noWebsite','No website','◇'],['highRated','4.5+ rating','★'],['phone','Phone available','⌕'],['unclaimed','Unclaimed','○']];
const plans=[['Free','500 leads','Free'],['Pro','10,000 leads','$29/mo'],['Business','50,000 leads','$79/mo']];
export default function Home(){
 const[location,setLocation]=useState('United States'),[region,setRegion]=useState(''),[query,setQuery]=useState('Dentists'),[limit,setLimit]=useState('20'),[reviews,setReviews]=useState('0'),[running,setRunning]=useState(false),[leads,setLeads]=useState<Lead[]>([]),[error,setError]=useState(''),[opportunity,setOpportunity]=useState<Opportunity>('all'),[selected,setSelected]=useState<Lead|null>(null),[lab,setLab]=useState(true),[complete,setComplete]=useState(false),[credits,setCredits]=useState(500),[showPlans,setShowPlans]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem('mapleads-credits');if(saved)setCredits(Number(saved));},[]);
 const area=region||location;
 const filtered=useMemo(()=>leads.filter(l=>opportunity==='all'||(opportunity==='noWebsite'?!l.website:opportunity==='highRated'?Number(l.rating||0)>=4.5:opportunity==='phone'?Boolean(l.phone):l.claimed===false)),[leads,opportunity]);
 const stats=useMemo(()=>({web:leads.filter(l=>l.website).length,phone:leads.filter(l=>l.phone).length,high:leads.filter(l=>Number(l.rating||0)>=4.5).length}),[leads]);
 const selectCountry=(v:string)=>{setLocation(v);setRegion('');setLeads([]);setComplete(false);setSelected(null)};
 const search=async(searchQuery=query,searchArea=area)=>{if(credits<=0){setShowPlans(true);return}setRunning(true);setError('');setComplete(false);setSelected(null);try{const requested=Math.min(Math.max(Number(limit)||20,1),credits);const r=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:searchQuery.trim(),location:searchArea,limit:requested,minReviews:Number(reviews)||0})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Search failed');const unique:Lead[]=Array.from(new Map<string,Lead>((d.leads||[]).map((l:Lead)=>[l.place_id||`${l.name}-${l.address}`,l])).values()).slice(0,requested);const spent=unique.length;const next=Math.max(0,credits-spent);setLeads(unique);setCredits(next);localStorage.setItem('mapleads-credits',String(next));setComplete(true);setLab(false);}catch(e){setError(e instanceof Error?e.message:'Search failed')}finally{setRunning(false)}};
 const smart=()=>{const m=query.match(/^(.*?)\s+in\s+(.+)$/i);if(m){const nextQuery=m[1].trim(),nextRegion=m[2].trim();setQuery(nextQuery);setRegion(nextRegion);search(nextQuery,nextRegion)}else search()};
 const csv=()=>{const fields=['query','name','phone','review_count','rating','categories','city','state','website','domain','email','address','business_status','claimed','working_hours','google_maps_url','zip_code'];const rows=filtered.map(l=>fields.map(k=>`"${String((l as any)[k]??'').replaceAll('"','""')}"`).join(','));const blob=new Blob([[fields.join(','),...rows].join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mapleads-${query}-${area}.csv`;a.click();URL.revokeObjectURL(a.href)};
 return <main className="shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark">M</div><div><b>MapLeads</b><span>Explore · Discover · Export</span></div></div><div className="workspace"><span>WORKSPACE</span><button>MAIN</button></div><nav><button className="nav active"><span>＋</span> Explore</button><button className="nav" onClick={()=>setLab(false)}><span>◫</span> Leads <em>{leads.length}</em></button><button className="nav"><span>◷</span> Searches</button><button className="nav"><span>⇩</span> Exports</button><button className="nav"><span>⚙</span> Settings</button></nav><div className="sidebar-note"><b>Lead intelligence</b><span>Search markets, find prospects, export clean data.</span></div><div className="credits"><div><span>Credits</span><b>{credits}</b></div><div className="bar"><i style={{width:`${credits/5}%`}}/></div><small>{credits} / 500 free leads</small><button onClick={()=>setShowPlans(true)}>Upgrade</button></div></aside>
  <section className="workspace-main"><header className="topbar"><div><span className="crumb">MAPLEADS</span><strong> / Explore</strong></div><div className="command"><span>⌘K</span><input placeholder="Try: dentists in London" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&smart()}/><button onClick={smart}>Search</button></div><div className="online"><i/> Live Places</div></header>
   <div className="map-stage"><MapCanvas location={location} onLocation={selectCountry} leads={filtered}/><div className="map-title"><span>GLOBAL LEAD EXPLORER</span><h1>{complete?`${filtered.length.toLocaleString()} leads found`:'Find businesses anywhere'}</h1><p>{complete?`${query} · ${area}`:'Country → location → query → leads'}</p></div><div className="map-actions"><button onClick={()=>setLab(true)}>＋ Search</button>{leads.length>0&&<button onClick={csv}>⇩ Export CSV</button>}<button onClick={()=>setShowPlans(true)}>Credits · {credits}</button></div>{running&&<div className="scan-card"><div className="scan-orbit"/><div><span>EXTRACTING BUSINESS DATA</span><b>{query}</b><small>{area} · Google Places</small></div><strong className="scan-number">•••</strong></div>}{complete&&!running&&<div className="map-stats"><div><b>{filtered.length}</b><span>Leads</span></div><div><b>{stats.web}</b><span>Websites</span></div><div><b>{stats.phone}</b><span>Phones</span></div><div><b>{stats.high}</b><span>4.5+ rated</span></div></div>}<div className="map-hint"><span className="pulse"/> {complete?'Select a lead or export your list':'Drag, zoom and click a country to begin'}</div></div>
   <aside className={`search-lab ${lab?'open':''}`}><div className="lab-head"><div><span>SEARCH LAB</span><h2>Define your market</h2></div><button onClick={()=>setLab(false)}>×</button></div><label>COUNTRY</label><div className="country-select"><span>◎</span><select value={location} onChange={e=>selectCountry(e.target.value)}>{countries.map(c=><option key={c}>{c}</option>)}</select></div><label>LOCATION</label><div className="input-wrap"><span>⌖</span><input value={region} onChange={e=>setRegion(e.target.value)} placeholder="City, district, neighborhood..."/><button className="input-clear" onClick={()=>setRegion('')}>×</button></div><div className="examples"><div className="examples-title">Popular locations</div><div className="example-list">{examples.map(x=><button key={x} className="example-chip" onClick={()=>setRegion(x)}>{x}</button>)}</div></div><div className="zone-row"><div><b>{area}</b><small>{region?`Location within ${location}`:`Entire ${location}`}</small></div></div><label>BUSINESS QUERY</label><div className="big-input"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="dentists, hotels, restaurants..."/><kbd>↵</kbd></div><div className="suggestions"><button onClick={()=>setQuery('Dentists')}>Dentists</button><button onClick={()=>setQuery('Hotels')}>Hotels</button><button onClick={()=>setQuery('Restaurants')}>Restaurants</button><button onClick={()=>setQuery('Manufacturers')}>Manufacturers</button></div><label>OPPORTUNITY FILTER</label><div className="opportunity-grid">{filters.map(([id,label,icon])=><button key={id} className={opportunity===id?'active':''} onClick={()=>setOpportunity(id)}><span>{icon}</span>{label}</button>)}</div><label>RESULT LIMIT</label><div className="two-col"><div><span>Leads</span><input className="field" type="number" min="1" max="100" value={limit} onChange={e=>setLimit(e.target.value)}/></div><div><span>Min reviews</span><input className="field" type="number" min="0" value={reviews} onChange={e=>setReviews(e.target.value)}/></div></div>{error&&<div className="error-box">{error}</div>}<button className="hunt" onClick={()=>search()} disabled={running||credits<=0}><span>{running?'Extracting...':credits<=0?'Upgrade to continue':`Discover ${query}`}</span><b>→</b></button><small className="lab-foot">1 successfully extracted unique business = 1 lead credit.</small></aside>
   {complete&&<section className="results-dock"><div className="results-head"><div><span>DISCOVERY RESULTS</span><h2>{filtered.length.toLocaleString()} businesses</h2></div><div className="result-actions"><button onClick={()=>setOpportunity('all')}>Clear filters</button><button className="dark" onClick={csv}>Export CSV</button></div></div><div className="result-list">{filtered.slice(0,12).map((l,i)=><button className={`lead-card ${selected?.place_id===l.place_id?'selected':''}`} key={l.place_id||i} onClick={()=>setSelected(l)}><span className="lead-rank">{String(i+1).padStart(2,'0')}</span><span className="lead-main"><b>{l.name}</b><small>{l.city}{l.state?`, ${l.state}`:''} · {l.categories?.slice(0,1).join('')}</small></span><span className="lead-score">{l.rating?`★ ${l.rating}`:'—'}<small>{l.review_count} reviews</small></span><span className="lead-arrow">→</span></button>)}</div>{selected&&<div className="lead-detail"><div><span>SELECTED LEAD</span><h3>{selected.name}</h3><p>{selected.address}</p></div><div className="detail-grid"><span><b>{selected.rating||'—'}</b> rating</span><span><b>{selected.review_count}</b> reviews</span><span><b>{selected.phone?'✓':'—'}</b> phone</span><span><b>{selected.website?'✓':'—'}</b> website</span></div><button onClick={()=>setSelected(null)}>×</button></div>}</section>}
  </section>
  {showPlans&&<div className="modal-backdrop" onClick={()=>setShowPlans(false)}><div className="pricing-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setShowPlans(false)}>×</button><span>MAPLEADS PLANS</span><h2>Keep exploring every market.</h2><p>Start with 500 free leads. Upgrade for higher monthly lead limits.</p><div className="plan-grid">{plans.map((p,i)=><div className={`plan ${i===1?'featured':''}`} key={p[0]}><b>{p[0]}</b><strong>{p[2]}</strong><span>{p[1]}</span><button onClick={()=>setShowPlans(false)}>{i===0?'Current plan':'Upgrade'}</button></div>)}</div><small>Pricing and monthly limits are configurable for production billing.</small></div></div>}
 </main>
}
