"use client";
import { useEffect, useMemo, useState } from 'react';
import { ComposableMap, Geographies, Geography, ZoomableGroup, Marker } from '@vnedyalk0v/react19-simple-maps';
import countries from 'world-atlas/countries-110m.json';
import { feature } from 'topojson-client';

type Lead={name:string;lat:number|null;lng:number|null;rating:number|null;review_count:number;city:string;state:string;domain:string};
type Props={location:string;onLocation:(name:string)=>void;leads?:Lead[]};
type CountryFeature={type:string;id?:string|number;properties?:Record<string,string|number|undefined>;geometry:unknown};
type Topology={objects:{countries:unknown}};
const fallback:Record<string,string>={'356':'India','840':'United States','124':'Canada','826':'United Kingdom','36':'Australia','276':'Germany','392':'Japan','76':'Brazil','156':'China'};
const focus:Record<string,[number,number,number]>={India:[78.96,20.59,3.0],'United States':[-100,39,2.25],Canada:[-106,57,2.0],'United Kingdom':[-3,55,5.0],Australia:[134,-25,2.5],Germany:[10.4,51.2,5.0],France:[2,46,4.4],Singapore:[103.8,1.35,10],Japan:[138,36,4.0],China:[104,35,2.7],Brazil:[-52,-10,2.3],'United Arab Emirates':[54,24,7],'Saudi Arabia':[45,24,3.5],'South Africa':[24,-30,3]};
export default function Globe({location,onLocation,leads=[]}:Props){const[view,setView]=useState<[number,number,number]>([0,20,1]);const[hover,setHover]=useState('');const geo=useMemo(()=>{const t=countries as unknown as Topology;return(feature(t as never,t.objects.countries as never) as any).features as CountryFeature[]},[]);const nameOf=(d:CountryFeature)=>String(d.properties?.name||d.properties?.NAME||d.properties?.ADMIN||fallback[String(d.id??'')]||'Region');const selected=(d:CountryFeature)=>nameOf(d).toLowerCase()===location.toLowerCase();useEffect(()=>{setView(focus[location]||[0,20,1])},[location]);return <div className="flat-map"><ComposableMap projection="geoEqualEarth" projectionConfig={{scale:145}} width={900} height={520} style={{width:'100%',height:'100%'}}><ZoomableGroup center={[view[0],view[1]]} zoom={view[2]} minZoom={0.7} maxZoom={9} onMoveEnd={({coordinates,zoom}:any)=>setView([coordinates[0],coordinates[1],zoom])}><Geographies geography={countries as any}>{({geographies}:any)=>geographies.map((geo:any)=><Geography key={geo.rsmKey} geography={geo} onMouseEnter={()=>setHover(nameOf(geo))} onMouseLeave={()=>setHover('')} onClick={()=>{const n=nameOf(geo);onLocation(n);setView(focus[n]||[0,20,1.5])}} style={{default:{fill:selected(geo)?'#bcebd6':'#ffffff',stroke:selected(geo)?'#087c56':'#82bda7',strokeWidth:selected(geo)?1.8:0.7,outline:'none'},hover:{fill:'#e4f7ef',stroke:'#0f9f6e',strokeWidth:1.5,outline:'none'},pressed:{fill:'#9ddcbd',outline:'none'}}}/>)} </Geographies>{leads.filter(l=>l.lat!=null&&l.lng!=null).map((l,i)=><Marker key={`${l.name}-${i}`} coordinates={[l.lng as number,l.lat as number]}><circle r={4} fill="#0f9f6e" stroke="#fff" strokeWidth={1.5}/><title>{l.name} · {l.rating??'—'}★ · {l.review_count} reviews</title></Marker>)}</ZoomableGroup></ComposableMap><div className="globe-overlay"><span>{leads.length?'LIVE DISCOVERY MAP':'EXPLORE THE MARKET'}</span><b>{location}</b><small>{hover?`Hovering ${hover}`:'Click a country, zoom, or search an area to begin.'}</small></div><div className="map-tools"><button className="world-reset" onClick={()=>setView([0,20,1])}>⌖ World view</button>{leads.length>0&&<span className="map-result-badge">● {leads.length} discovered</span>}</div><div className="map-legend"><span><i className="legend-dot selected-dot"/> Selected</span><span><i className="legend-dot border-dot"/> Countries</span>{leads.length>0&&<span><i className="legend-dot lead-dot"/> Leads</span>}</div></div>}